### PR TITLE
 Improve Development Environment Guidance

### LINKED ISSUE #1: Improve Development Environment Guidance
## Description

The current process for setting up a development environment lacks clarity and automation. This can lead to confusion and slow down the development workflow. Improving documentation, automation, and troubleshooting guidance will enhance the developer experience.

## Expected Outcome  
- A clear understanding of the required dependencies and setup commands for both VM1 and VM2.  
- Comprehensive troubleshooting guidance for common issues, including network-related problems.  
- Partial automation of the development environment setup process to streamline workflows.  

## Tasks  

- Improve Documentation  
  - Provide step-by-step instructions for setting up each virtual machine (e.g., ION on VM1 and µD3TN on VM2).  
  - Include required commands, file paths, and detailed configuration settings.  
  - Develop a dedicated `TROUBLESHOOT.md` file:  
    - Recommend tools for debugging configuration and runtime issues.  
    - Provide solutions for common errors and misconfigurations.  
- Get a valid `host.rc` File for ION  
  - Add command to automate the generation of a valid `host.rc` file using three parameters:  
    - VM1 IP address  
    - VM2 IP address  
    - Selected convergence layer protocol  
  - Alternatively, supply sample `host.rc` files.

### PR DESCRIPTION
**Pull request by sylvain-pierrot**
# Description

This pull request aims to improve development environment guidance on several aspects. The final architecture is composed of two VMs (ion-node & ud3tn-node). So, the goal is to get a quick-start by providing a `cloud-init` file for each node and a `host.rc` file for ION, and get a clear documentation.

Fixes #1 

## Checklist : Improvements

- [X] Use [Just](https://github.com/casey/just) to generate configuration files
  - Generate an ION host.rc file
  - Generate cloud-init file for ud3tn-node
  - Generate cloud-init file for ion-node
  - Use [Jinja2](https://jinja.palletsprojects.com/en/stable/) for templating with Just 
- [X] Improve documentation
  - Restructure README.md
  - Add a Table of Contents in README.md
  - Add a `Getting started` section in README.md
    - Explain the quick-start process (using QEMU/KVM, cloud-init, Just commands, and manual commands)
  - Include a `TROUBLESHOOTING.md` file

## Additional changes

- [X] Fix an issue in the `bp-daemon` Makefile
- [X] Added a `host.ionconfig` file at the root directory (required for use by `host.rc`)
- [X] Add .gitignore file
- [X] Update demo app in userspace to pass the EID as a parameter

# How to test

```bash
# Generate an ION host.rc
just ion host 192.168.122.140 192.168.122.182 > host.rc

# Generate cloud-init file for ud3tn-node
SSH_PUBLIC_KEY="ssh-rsa AAA...." just cloud-config ud3tn-node

# Generate cloud-init file for ion-node
SSH_PUBLIC_KEY="ssh-rsa AAA...." just cloud-config ion-node
```

### CODE REVIEW

**Comment by juanfraire** [comment]
Thanks for looking into this, Sylvain. I'm happy to review once all push are there.

**Comment by sylvain-pierrot** [comment]
> Thanks for looking into this, Sylvain. I'm happy to review once all push are there.

It's a pleasure to work on this project. This PR is ready for review; please let me know for any suggestions or remarks.

**Comment by juanfraire** [comment]
Thanks a lot for this excellent work, Sylvain. Please feel free to reach me to juanfraire@gmail.com if needed.

**Comment by sylvain-pierrot** [comment]
Thank you, I will remember!

**Pull request merged**
